name: Hello World Workflow

on: [push]

jobs:
    hellow_world_job:
        run-on: ubuntu-latest

        strp:
        - name: Checkout repository content
          uses: actions/checkout@v4

        - name: Run a one-line script
          run: echo "Hello, World!"

